### ISSUE TITLE
when only using fixed ratio, the ratio can randomly change

### ISSUE THREAD

**Issue by halpz** [guoyingtao/Mantis#52] opened 2020-08-26 12:08 UTC
when using config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 4.0 / 3.0) , it appears to be fixed at first, but after some zooming and cropping, the ratio can change randomly

**Comment by guoyingtao** [comment] 2020-08-26 15:10
@halpz Thanks for the feedback. How often does it happen? Can you reproduce it every time? Thank you!

**Comment by edbarbier** [comment] 2021-03-22 18:38
I'm notifing the same problem when I add a customRatio (in my case 16/9), if I do not resize, or crop the image and just tap Done. The correct aspect ratio is maintained, otherwise the images appears too wide, and thin.
```
var config = Mantis.Config()
config.addCustomRatio(byHorizontalWidth: 16, andHorizontalHeight: 9)
config.ratioOptions = [.custom, .square, .original]
config.cropVisualEffectType = .blurDark
cropViewController = Mantis.cropViewController(image: UIImage(), config: config)
```
He's an example if that helps. Both images should get a 16 by 9 ration, the one I slightly edited after opening the CropViewController appears like a long panorama.

![image](https://user-images.githubusercontent.com/11492000/112040903-0b63e600-8b46-11eb-8b3a-df91730b40eb.png)

**Comment by guoyingtao** [comment] 2021-03-23 01:55
@edbarbier Thanks for the feedback. I still could not reproduce it. Would you mind posting the photos you are using here? Thank you very much!

**Comment by edbarbier** [comment] 2021-03-23 12:36
Strangly, after trying again this morning I couldn't reproduce it. 

I remember panning / pinching on the image before tapping done and experiencing the bug yesterday. In the .zip you'll find the two images I was using in the previous screenshot.

[Archive.zip](https://github.com/guoyingtao/Mantis/files/6189591/Archive.zip)

I'm not done working on this project so as I do more testing, I'll report back if I get more info about this issue.

**Comment by guoyingtao** [comment] 2021-04-23 18:16
@edbarbier I think the new release of Mantis fixed this issue so I close this issue for now. You can reopen it if you reproduce it again.

**Comment by alvinthen** [comment] 2021-05-10 06:12
I was able to reproduce this consistently on my side, on 1.7.1, after zooming and panning, the transformation mask frame returned has a different size. I think it's mainly rounding adjustments. Is there a way to provide the CropViewController a mask frame size instead of calculating from the aspect ratio, and maintain that frame size?

```
The first Transformation maskFrame to get the aspect ratio: (18.364800000000002, 14.0, 338.2704, 507.0)
The next Transformation maskFrame: (17.484375, 14.0, 340.03125, 507.0)
```

**Comment by guoyingtao** [comment] 2021-05-11 04:13
@alvinthen I made more changes for it
Can you check if the commit below solve the problem? Thank you!
pod 'Mantis', :git => 'https://github.com/guoyingtao/Mantis.git', :commit => 'f4ffee0b0658647a8d2a579898a5e3c72a3bb3fe'

**Comment by alvinthen** [comment] 2021-05-11 05:49
Appreciate it again! Both aspect ratio of the `cropped` is not identical, I may have put us on the wrong path, it wouldn't be identical at all, given the number of fractions. Not sure if this library should do rounding on the frame of the `cropped` image.

It's close enough to fit our use case now. Thanks!

**Comment by alvinthen** [comment] 2021-05-11 06:24
Actually, it seems that with that fix, we can no longer move the crop box to the edges

**Comment by guoyingtao** [comment] 2021-05-11 13:42
@alvinthen Would you mind posting a screenshot or a video to show the issue?

**Comment by alvinthen** [comment] 2021-05-19 13:02
I think this is a pretty edge case.

In `cropViewControllerDidCrop`, I get the ratio from the first crop like this

```swift
self.ratio = Double(cropped.size.width / cropped.size.height)
```

Then, I send this ratio back for the second image

```swift
config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: ratio)
```

The ratio of the first resulted in 0.5648232094288305, the second 0.5637319316688568. It's just fractionally different, but enough to affect our use case.

https://user-images.githubusercontent.com/771989/118816014-5c911b80-b8e4-11eb-9a26-5aaa298cbfc7.MP4

---

As for the crop box to edges issues with that commit, see the video below, notice I could not pan to the most bottom edge of the picture

https://user-images.githubusercontent.com/771989/118816883-38820a00-b8e5-11eb-8edf-b8f65eebe8fe.MP4

Anyways, I honestly think there's isn't much to do with Mantis. I'm fine if you want to close this.

**Comment by guoyingtao** [comment] 2021-05-19 20:51
@alvinthen OK. I will close it then. Hope you can figure out a way to finish your feature.

**Closed by guoyingtao** 2021-05-19 20:51 UTC
Labels: bug
