### ISSUE TITLE
cannot install through cocoapods

### ISSUE THREAD

**Issue by MensikJan** [guoyingtao/Mantis#163] opened 2022-05-09 10:56 UTC
instalation fail and created empty folders, can you repair it?

**Comment by guoyingtao** [comment] 2022-05-09 13:21
Hi @MensikJan 

Thanks for the feedback

Can you please provide the following information?
* CocoaPods version
* Mantis version
* Xcode version
* macOS version

Thank you!

**Comment by MensikJan** [comment] 2022-05-10 08:08
Hi,
MacOS 12.1
cocoapods-1.11.3
Mantis 1.9.0
Xcode 13.3

**Comment by guoyingtao** [comment] 2022-05-12 09:14
Hi @MensikJan 
I can't reproduce this issue. Can you try Swift Package Manager?

**Comment by guoyingtao** [comment] 2022-08-08 16:24
Since I haven't got response for this issue for a long time. I close it for now.

**Closed by guoyingtao** 2022-08-08 16:24 UTC
Labels: question
